# -*- coding: utf-8 -*-
"""Copia de openai-chatbot-with-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12trMJPB50hGLZvepS3JGztwgOgXzWDAY
"""

import streamlit as st
import openai

# Setup your OpenAI API key (hardcoded for testing; avoid en producción)
openai.api_key = "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"

st.set_page_config(page_title="AI Assistant", page_icon="🤖")
st.title("🤖 AI Assistant App")
st.markdown("Ask anything and get answers powered by OpenAI GPT.")

if "messages" not in st.session_state:
    st.session_state.messages = []

def get_response(prompt: str, model: str = "gpt-4", max_tokens: int = 150) -> str:
    try:
        response = openai.ChatCompletion.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are a helpful AI assistant."},
                *st.session_state.messages,
                {"role": "user", "content": prompt}
            ],
            max_tokens=max_tokens,
            temperature=0.7,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"⚠️ Error: {str(e)}"

user_input = st.text_input("Your question:")

if user_input:
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.spinner("Thinking..."):
        answer = get_response(user_input)
    st.session_state.messages.append({"role": "assistant", "content": answer})
    st.experimental_rerun()

for msg in st.session_state.messages:
    if msg["role"] == "user":
        st.markdown(f"**You:** {msg['content']}")
    else:
        st.markdown(f"**AI:** {msg['content']}")

# 1️⃣ Install required packages
!pip install streamlit pyngrok

# 2️⃣ Create the app.py file manually
app_code = '''
import streamlit as st

st.set_page_config(page_title="AI Assistant Demo", page_icon="🤖")
st.title("🤖 AI Assistant Demo (Colab + ngrok)")

user_input = st.text_input("Ask me anything:")
if user_input:
    st.write("You asked:", user_input)
'''

with open("app.py", "w") as f:
    f.write(app_code)

# 3️⃣ Start Streamlit app in background
import subprocess
cmd = ["streamlit", "run", "app.py", "--server.port", "8501", "--server.headless", "true"]
proc = subprocess.Popen(cmd)

# 4️⃣ Configure ngrok authtoken (replace YOUR_AUTHTOKEN here!)
!ngrok config add-authtoken 2zgCWOeQbPbIRCWnX5Qqers5FZx_g4Y5WHarZyxAfc1Tkbsr

# 5️⃣ Create ngrok tunnel
from pyngrok import ngrok
public_url = ngrok.connect("http://localhost:8501")
print(f"🚀 Your Streamlit app is live at: {public_url}")

#Clean tunnels
!kill $(pgrep ngrok)
!kill $(pgrep streamlit)